var DataGeneratorV1 = require('./DataGeneratorV1');
var CreateTable = require('./CreateTable');
var DeleteTable = require('./DeleteTable');
var QueryLambda = require('./QueryLambda');
var config = require('./ReadConfig');
var CreateLambda = require('./CreateLambda');
var QueryLambdaSize = require('./QueryLambdaSize');
// CreateTable.CreateSampleTables(config);
// DataGeneratorV1.GenerateTable(config);
// DeleteTable.DeleteSampleTables(config);
// QueryLambda.ImportDataSample(config);
// CreateLambda.createLambdaRun();
QueryLambdaSize.testLambdaSize();
